// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProjekat.Models;

namespace WebProjekat.Migrations
{
    [DbContext(typeof(ProdavnicaContext))]
    [Migration("20220317195231_V5")]
    partial class V5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebProjekat.Models.Magacin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrMagacina")
                        .HasColumnType("int");

                    b.Property<int>("Kolona")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Vrsta")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Magacin");
                });

            modelBuilder.Entity("WebProjekat.Models.Proizvod", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Marka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NazivMagacina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProizvodRafID")
                        .HasColumnType("int");

                    b.Property<int?>("RafID")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("ProizvodRafID");

                    b.HasIndex("RafID");

                    b.ToTable("Proizvod");
                });

            modelBuilder.Entity("WebProjekat.Models.Raf", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojProizovda")
                        .HasColumnType("int");

                    b.Property<int?>("MagacinID")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxBrProizovda")
                        .HasColumnType("int");

                    b.Property<string>("NazivMagacina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MagacinID");

                    b.ToTable("Raf");
                });

            modelBuilder.Entity("WebProjekat.Models.Spoj", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojProizovda")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxBrProizovda")
                        .HasColumnType("int");

                    b.Property<string>("NazivMagacina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RafID")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RafID");

                    b.ToTable("Spoj");
                });

            modelBuilder.Entity("WebProjekat.Models.Proizvod", b =>
                {
                    b.HasOne("WebProjekat.Models.Spoj", "ProizvodRaf")
                        .WithMany("Proizvod")
                        .HasForeignKey("ProizvodRafID");

                    b.HasOne("WebProjekat.Models.Raf", "Raf")
                        .WithMany()
                        .HasForeignKey("RafID");

                    b.Navigation("ProizvodRaf");

                    b.Navigation("Raf");
                });

            modelBuilder.Entity("WebProjekat.Models.Raf", b =>
                {
                    b.HasOne("WebProjekat.Models.Magacin", "Magacin")
                        .WithMany("ProizvodiRafovi")
                        .HasForeignKey("MagacinID");

                    b.Navigation("Magacin");
                });

            modelBuilder.Entity("WebProjekat.Models.Spoj", b =>
                {
                    b.HasOne("WebProjekat.Models.Raf", "Raf")
                        .WithMany("RafProizvod")
                        .HasForeignKey("RafID");

                    b.Navigation("Raf");
                });

            modelBuilder.Entity("WebProjekat.Models.Magacin", b =>
                {
                    b.Navigation("ProizvodiRafovi");
                });

            modelBuilder.Entity("WebProjekat.Models.Raf", b =>
                {
                    b.Navigation("RafProizvod");
                });

            modelBuilder.Entity("WebProjekat.Models.Spoj", b =>
                {
                    b.Navigation("Proizvod");
                });
#pragma warning restore 612, 618
        }
    }
}
